---
# vars file for

#Bare ubuntu 16.04 LTS in Ireland Region
image: "ami-add175d4"

instance_type: "t2.micro"
region: "eu-west-1"
elb_name: "apache-tomcat-rajen"

group_id: "sg-a9d358d2"

vpc_id: "vpc-a5a6d5c2"

key_name: "pramerica"

subnets:
    - { az: "eu-west-1a", subnet_id: "subnet-5841283f", instance_count: "1"}
    - { az: "eu-west-1b", subnet_id: "subnet-907707d9", instance_count: "1"}
    - { az: "eu-west-1c", subnet_id: "subnet-64e4513f", instance_count: "1"}

elb_subnets: ["subnet-5841283f","subnet-907707d9","subnet-64e4513f"]

elb_zones: ["eu-west-1a","eu-west-1b","eu-west-1c"]

termination_protection: "no"
ebs_optimized: "true"
device_name: "/dev/sda1"
volume_size: "10"
volume_type: "gp2"

launch_configuration_name: "apache-tomcat-rajen"
asg_name: "apache-tomcat-rajen"
asg_size_min: "3"
asg_size_max: "3"
desired_capacity: "3"
health_check_period: "30"

count_tag: "apache_tomcat_rajen_2017-11-23"
instance_tags: "apache_tomcat_rajen_2017-11-23"
